using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace UretimVeYonetimOtomasyon
{
    public partial class frmUretilenIsEmirleri : Form
    {
        public frmUretilenIsEmirleri()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void frmUretilenIsEmirleri_Load(object sender, EventArgs e)
        {
            gridView1.OptionsBehavior.Editable = false;
        }
    }
}
